# 🚀 Railway Deployment Configuration
[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm ci && npm run build"

[deploy]
startCommand = "node backend/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[service]
port = 5000

[nixpacks]
engines = { node = "18" }