[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[service]
port = 5000

[nixpacks]
engines = { node = "18.x" }