[build]
builder = "nixpacks"
buildCommand = "npm install --prefix backend && npm run build --prefix backend"

[deploy]
startCommand = "npm run start:prod --prefix backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[service]
port = 5000

[nixpacks]
node_version = "18.x"