[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build"
nixpacksConfig = { nodejs = "18.x" }

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[service]
port = 5000